### ISSUE TITLE
Move common workflows from actions to .github repo

### ISSUE THREAD

**Issue by ahwagner** [biocommons/.github#1]
We looked at this example today:

https://github.com/biocommons/.github/blob/84ebe4c83c3b54271a5938e5050a16651afc396e/.github/workflows/stale.yml#L11

We should update the above to have the `stale.yml` and other workflows in the same .github repo for Biocommons standard templates.

**Comment by reece** [comment]
Done. See README.md for details.

Also, Actions tab now shows these available workflows so far:

![image](https://github.com/biocommons/.github/assets/109453/5ee8e5ab-63fc-43a2-ba6d-ad49dfeda859)
